import { Button, VerticalBox , HorizontalBox, LineEdit} from "std-widgets.slint";

export component AppWindow inherits Window {
    callback divide-income(string);

    in-out property<int> amount: 0;
    in property<string> result : "";
    GridLayout {
        padding: 50px;
        spacing: 25px;
    Row {
        Text {
            text: "Enter Total Income";
            horizontal-alignment: center;
            font-size: 24px;
            font-weight: 900;
        }
    }
    Row {
        income := LineEdit {
            horizontal-alignment: center;
            font-size: 16px;
            placeholder-text: "Enter your Income";
        }
    }
    Row {
        Button {
            text: "Calculate";
            primary: true;
            clicked => {
                root.divide-income(income.text);
            }
        }
    }

    Row {
       VerticalBox {
        Rectangle {
            height: 100px;
            Text {
                text: root.result;
                color: black;
                font-size: 16px;
                font-weight: 500;
            }
        }
       }
    }

    }
}
